=== sumitbhatia101/CopyRestAssuredAutomationFramework/src/test/resources/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
      "type": "string"
    },
    "email": {
      "type": "string"
    },
    "address": {
      "type": "object",
      "properties": {
        "street_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "postal_code": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "street_address",
        "city",
        "state",
        "postal_code",
        "country"
      ]
    },
    "favorite_foods": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    }
  },
  "required": [
    "id",
    "first_name",
    "last_name",
    "email",
    "address",
    "favorite_foods"
  ]
}

=== sumitbhatia101/CopyRestAssuredAutomationFramework/output/postRequestUsingExternalFileresponse.json
{
  "id": "8155",
  "first_name": "Rubye",
  "last_name": "lastname",
  "email": "emailf.emaill@example.com",
  "address": {
    "street_address": "84545 Bakwas Ave",
    "city": "Anycity",
    "state": "NY",
    "postal_code": "457",
    "country": "USA"
  },
  "favorite_foods": [
    "Shit",
    "Poop",
    "Scat"
  ]
}
